#Connecting to my servers
alias munrig="ssh muniter@10.3.30.10"
alias munrig_e="ssh muniter@muniter.xyz"
alias munrig_sftp="sftp muniter@10.3.30.10"
alias galoserver="ssh gales@muniter.duckdns.org"
alias ubnt="ssh muniter@muniter.duckdns.org -p 2200 -i ~/.ssh/ubnt1_rsa"
alias droplet="ssh root@wiki.muniter.xyz"
alias i3c="vim $HOME/.config/i3/config"
alias vr="vim $HOME/.vimrc"
alias df="df -x squashfs"
alias ryzenon="ssh pi sudo etherwake -i eth0 30:9c:23:a6:af:74 && echo 'Magick Packet sent' "
alias pi="ssh pi"
alias nn="nnn ~/Sync/notes"
#alias dokudata="sudo sshfs -o allow_other,default_permissions,IdentityFile=$HOME/.ssh/id_rsa root@wiki.muniter.xyz:/var/lib/docker/volumes/root_dokuwiki_personal_data/_data/dokuwiki/data $HOME/projects/dokuwiki_data"
